use super::{ArcanaType, Ohang, Suit, TarotCard, TarotElement};

/// 메이저 아르카나 22장
static MAJOR_ARCANA: [TarotCard; 22] = [
    TarotCard {
        id: 0,
        name_ko: "바보",
        name_en: "The Fool",
        arcana: ArcanaType::Major,
        suit: None,
        number: 0,
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 1,
        name_ko: "마법사",
        name_en: "The Magician",
        arcana: ArcanaType::Major,
        suit: None,
        number: 1,
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 2,
        name_ko: "여사제",
        name_en: "The High Priestess",
        arcana: ArcanaType::Major,
        suit: None,
        number: 2,
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 3,
        name_ko: "여제",
        name_en: "The Empress",
        arcana: ArcanaType::Major,
        suit: None,
        number: 3,
        element: TarotElement::Earth,
        ohang: Ohang::Earth,
    },
    TarotCard {
        id: 4,
        name_ko: "황제",
        name_en: "The Emperor",
        arcana: ArcanaType::Major,
        suit: None,
        number: 4,
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 5,
        name_ko: "교황",
        name_en: "The Hierophant",
        arcana: ArcanaType::Major,
        suit: None,
        number: 5,
        element: TarotElement::Earth,
        ohang: Ohang::Earth,
    },
    TarotCard {
        id: 6,
        name_ko: "연인",
        name_en: "The Lovers",
        arcana: ArcanaType::Major,
        suit: None,
        number: 6,
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 7,
        name_ko: "전차",
        name_en: "The Chariot",
        arcana: ArcanaType::Major,
        suit: None,
        number: 7,
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 8,
        name_ko: "힘",
        name_en: "Strength",
        arcana: ArcanaType::Major,
        suit: None,
        number: 8,
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 9,
        name_ko: "은둔자",
        name_en: "The Hermit",
        arcana: ArcanaType::Major,
        suit: None,
        number: 9,
        element: TarotElement::Earth,
        ohang: Ohang::Earth,
    },
    TarotCard {
        id: 10,
        name_ko: "운명의 수레바퀴",
        name_en: "Wheel of Fortune",
        arcana: ArcanaType::Major,
        suit: None,
        number: 10,
        element: TarotElement::Earth,
        ohang: Ohang::Earth,
    },
    TarotCard {
        id: 11,
        name_ko: "정의",
        name_en: "Justice",
        arcana: ArcanaType::Major,
        suit: None,
        number: 11,
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 12,
        name_ko: "매달린 사람",
        name_en: "The Hanged Man",
        arcana: ArcanaType::Major,
        suit: None,
        number: 12,
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 13,
        name_ko: "죽음",
        name_en: "Death",
        arcana: ArcanaType::Major,
        suit: None,
        number: 13,
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 14,
        name_ko: "절제",
        name_en: "Temperance",
        arcana: ArcanaType::Major,
        suit: None,
        number: 14,
        element: TarotElement::Earth,
        ohang: Ohang::Earth,
    },
    TarotCard {
        id: 15,
        name_ko: "악마",
        name_en: "The Devil",
        arcana: ArcanaType::Major,
        suit: None,
        number: 15,
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 16,
        name_ko: "탑",
        name_en: "The Tower",
        arcana: ArcanaType::Major,
        suit: None,
        number: 16,
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 17,
        name_ko: "별",
        name_en: "The Star",
        arcana: ArcanaType::Major,
        suit: None,
        number: 17,
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 18,
        name_ko: "달",
        name_en: "The Moon",
        arcana: ArcanaType::Major,
        suit: None,
        number: 18,
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 19,
        name_ko: "태양",
        name_en: "The Sun",
        arcana: ArcanaType::Major,
        suit: None,
        number: 19,
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 20,
        name_ko: "심판",
        name_en: "Judgement",
        arcana: ArcanaType::Major,
        suit: None,
        number: 20,
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 21,
        name_ko: "세계",
        name_en: "The World",
        arcana: ArcanaType::Major,
        suit: None,
        number: 21,
        element: TarotElement::Earth,
        ohang: Ohang::Earth,
    },
];

/// 완드(Wands) 수트 14장 - 불(Fire) - 화(火)
static WANDS: [TarotCard; 14] = [
    TarotCard {
        id: 22,
        name_ko: "완드 에이스",
        name_en: "Ace of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 1,
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 23,
        name_ko: "완드 2",
        name_en: "Two of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 2,
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 24,
        name_ko: "완드 3",
        name_en: "Three of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 3,
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 25,
        name_ko: "완드 4",
        name_en: "Four of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 4,
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 26,
        name_ko: "완드 5",
        name_en: "Five of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 5,
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 27,
        name_ko: "완드 6",
        name_en: "Six of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 6,
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 28,
        name_ko: "완드 7",
        name_en: "Seven of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 7,
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 29,
        name_ko: "완드 8",
        name_en: "Eight of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 8,
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 30,
        name_ko: "완드 9",
        name_en: "Nine of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 9,
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 31,
        name_ko: "완드 10",
        name_en: "Ten of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 10,
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 32,
        name_ko: "완드 시종",
        name_en: "Page of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 11,
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 33,
        name_ko: "완드 기사",
        name_en: "Knight of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 12,
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 34,
        name_ko: "완드 여왕",
        name_en: "Queen of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 13,
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 35,
        name_ko: "완드 왕",
        name_en: "King of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 14,
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
];

/// 컵(Cups) 수트 14장 - 물(Water) - 수(水)
static CUPS: [TarotCard; 14] = [
    TarotCard {
        id: 36,
        name_ko: "컵 에이스",
        name_en: "Ace of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 1,
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 37,
        name_ko: "컵 2",
        name_en: "Two of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 2,
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 38,
        name_ko: "컵 3",
        name_en: "Three of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 3,
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 39,
        name_ko: "컵 4",
        name_en: "Four of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 4,
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 40,
        name_ko: "컵 5",
        name_en: "Five of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 5,
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 41,
        name_ko: "컵 6",
        name_en: "Six of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 6,
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 42,
        name_ko: "컵 7",
        name_en: "Seven of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 7,
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 43,
        name_ko: "컵 8",
        name_en: "Eight of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 8,
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 44,
        name_ko: "컵 9",
        name_en: "Nine of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 9,
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 45,
        name_ko: "컵 10",
        name_en: "Ten of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 10,
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 46,
        name_ko: "컵 시종",
        name_en: "Page of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 11,
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 47,
        name_ko: "컵 기사",
        name_en: "Knight of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 12,
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 48,
        name_ko: "컵 여왕",
        name_en: "Queen of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 13,
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 49,
        name_ko: "컵 왕",
        name_en: "King of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 14,
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
];

/// 소드(Swords) 수트 14장 - 바람(Air) - 목(木)
static SWORDS: [TarotCard; 14] = [
    TarotCard {
        id: 50,
        name_ko: "소드 에이스",
        name_en: "Ace of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 1,
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 51,
        name_ko: "소드 2",
        name_en: "Two of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 2,
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 52,
        name_ko: "소드 3",
        name_en: "Three of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 3,
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 53,
        name_ko: "소드 4",
        name_en: "Four of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 4,
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 54,
        name_ko: "소드 5",
        name_en: "Five of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 5,
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 55,
        name_ko: "소드 6",
        name_en: "Six of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 6,
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 56,
        name_ko: "소드 7",
        name_en: "Seven of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 7,
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 57,
        name_ko: "소드 8",
        name_en: "Eight of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 8,
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 58,
        name_ko: "소드 9",
        name_en: "Nine of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 9,
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 59,
        name_ko: "소드 10",
        name_en: "Ten of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 10,
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 60,
        name_ko: "소드 시종",
        name_en: "Page of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 11,
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 61,
        name_ko: "소드 기사",
        name_en: "Knight of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 12,
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 62,
        name_ko: "소드 여왕",
        name_en: "Queen of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 13,
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 63,
        name_ko: "소드 왕",
        name_en: "King of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 14,
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
];

/// 펜타클(Pentacles) 수트 14장 - 땅(Earth) - 금(金)
static PENTACLES: [TarotCard; 14] = [
    TarotCard {
        id: 64,
        name_ko: "펜타클 에이스",
        name_en: "Ace of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 1,
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 65,
        name_ko: "펜타클 2",
        name_en: "Two of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 2,
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 66,
        name_ko: "펜타클 3",
        name_en: "Three of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 3,
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 67,
        name_ko: "펜타클 4",
        name_en: "Four of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 4,
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 68,
        name_ko: "펜타클 5",
        name_en: "Five of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 5,
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 69,
        name_ko: "펜타클 6",
        name_en: "Six of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 6,
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 70,
        name_ko: "펜타클 7",
        name_en: "Seven of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 7,
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 71,
        name_ko: "펜타클 8",
        name_en: "Eight of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 8,
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 72,
        name_ko: "펜타클 9",
        name_en: "Nine of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 9,
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 73,
        name_ko: "펜타클 10",
        name_en: "Ten of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 10,
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 74,
        name_ko: "펜타클 시종",
        name_en: "Page of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 11,
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 75,
        name_ko: "펜타클 기사",
        name_en: "Knight of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 12,
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 76,
        name_ko: "펜타클 여왕",
        name_en: "Queen of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 13,
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 77,
        name_ko: "펜타클 왕",
        name_en: "King of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 14,
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
];

/// 전체 78장 카드를 반환하는 함수
pub fn all_cards() -> &'static [TarotCard] {
    static ALL_CARDS: std::sync::OnceLock<Vec<TarotCard>> = std::sync::OnceLock::new();
    ALL_CARDS.get_or_init(|| {
        let mut cards = Vec::with_capacity(78);
        cards.extend_from_slice(&MAJOR_ARCANA);
        cards.extend_from_slice(&WANDS);
        cards.extend_from_slice(&CUPS);
        cards.extend_from_slice(&SWORDS);
        cards.extend_from_slice(&PENTACLES);
        cards
    })
}

/// 카드 ID로 카드 조회
pub fn get_card(id: u8) -> Option<&'static TarotCard> {
    all_cards().get(id as usize)
}
