use super::{ArcanaType, Ohang, Suit, TarotCard, TarotElement};

/// 메이저 아르카나 22장
static MAJOR_ARCANA: [TarotCard; 22] = [
    TarotCard {
        id: 0,
        name_ko: "바보",
        name_en: "The Fool",
        arcana: ArcanaType::Major,
        suit: None,
        number: 0,
        keywords: &["새로운 시작", "자유", "모험"],
        upright_meaning: "벼랑 끝에 선 것 같아도 지금 이 순간이 가장 용감한 출발점입니다. 계산보다 설렘을 앞세워 첫걸음을 내딛으세요. 순수한 눈으로 세상을 바라볼 때 가장 넓은 길이 열립니다.",
        reversed_meaning: "발이 앞서고 머리가 따라가지 못하고 있습니다. 흥분이 가라앉은 뒤에야 보이는 것들을 지금 미리 살펴보세요. 무모함과 용기는 한 끗 차이임을 기억하세요.",
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 1,
        name_ko: "마법사",
        name_en: "The Magician",
        arcana: ArcanaType::Major,
        suit: None,
        number: 1,
        keywords: &["의지", "창조", "능력"],
        upright_meaning: "필요한 모든 것이 이미 당신의 손안에 있습니다. 흩어진 재능을 한 방향으로 모으면 불가능해 보이던 일이 가능해집니다. 지금이 바로 의지를 현실로 바꿀 수 있는 때입니다.",
        reversed_meaning: "재능을 갈고닦는 대신 지름길을 찾고 있지는 않은지 돌아보세요. 눈에 보이는 결과만 쫓다 보면 진짜 실력이 자라지 않습니다. 정직한 방법이 가장 강한 마법입니다.",
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 2,
        name_ko: "여사제",
        name_en: "The High Priestess",
        arcana: ArcanaType::Major,
        suit: None,
        number: 2,
        keywords: &["직관", "비밀", "내면"],
        upright_meaning: "소음을 잠시 끄고 내면의 목소리에만 귀를 기울이는 시간입니다. 드러나지 않은 진실이 있고, 그것은 서두르지 않을 때 비로소 모습을 드러냅니다. 알 수 없다는 감각 자체가 하나의 답입니다.",
        reversed_meaning: "알면서도 모른 척하고 있는 것이 있습니다. 내면의 신호를 외면할수록 혼란만 커집니다. 불편한 진실을 마주할 용기가 길을 열어줄 것입니다.",
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 3,
        name_ko: "여제",
        name_en: "The Empress",
        arcana: ArcanaType::Major,
        suit: None,
        number: 3,
        keywords: &["풍요", "모성", "자연"],
        upright_meaning: "씨앗을 뿌리면 반드시 자라는 계절 속에 있습니다. 창조적 에너지가 차고 넘치니 그 흐름을 억누르지 말고 흘러가게 두세요. 돌봄을 주는 만큼 당신도 돌봄을 받을 자격이 있습니다.",
        reversed_meaning: "타인을 가득 채우면서 정작 자신의 빈 곳을 외면하고 있습니다. 자기 자신에게도 여제가 되어주세요. 넘치지 않으면 나눌 수도 없습니다.",
        element: TarotElement::Earth,
        ohang: Ohang::Earth,
    },
    TarotCard {
        id: 4,
        name_ko: "황제",
        name_en: "The Emperor",
        arcana: ArcanaType::Major,
        suit: None,
        number: 4,
        keywords: &["권위", "안정", "구조"],
        upright_meaning: "흔들리지 않는 기반이 있어야 자유롭게 나아갈 수 있습니다. 분명한 원칙과 체계적인 계획이 지금 당신에게 가장 강력한 무기입니다. 리더십은 통제가 아닌 책임에서 나옵니다.",
        reversed_meaning: "규칙이 수단이 아니라 목적이 되어버린 상황입니다. 고집과 원칙의 경계가 흐릿해지고 있습니다. 유연함을 잃으면 기반도 함께 흔들립니다.",
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 5,
        name_ko: "교황",
        name_en: "The Hierophant",
        arcana: ArcanaType::Major,
        suit: None,
        number: 5,
        keywords: &["전통", "가르침", "신앙"],
        upright_meaning: "이미 검증된 지혜 속에 지금 당신에게 필요한 답이 있습니다. 믿을 수 있는 스승이나 공동체가 길을 비춰줄 것입니다. 개인의 직관과 공동의 지혜를 함께 활용하세요.",
        reversed_meaning: "당연하다고 여겨온 것들을 다시 질문할 시간입니다. 틀을 깨는 것이 두려운 게 아니라, 틀 안에 갇힌 채로 멈추는 것이 더 두렵습니다. 자신만의 신념 체계를 세워보세요.",
        element: TarotElement::Earth,
        ohang: Ohang::Earth,
    },
    TarotCard {
        id: 6,
        name_ko: "연인",
        name_en: "The Lovers",
        arcana: ArcanaType::Major,
        suit: None,
        number: 6,
        keywords: &["사랑", "선택", "조화"],
        upright_meaning: "인생에서 몇 번 오지 않는 진심 어린 연결의 순간이 찾아왔습니다. 가슴이 이끄는 방향과 이성이 가리키는 방향을 함께 살펴보세요. 이 선택이 당신이 어떤 사람인지를 보여줍니다.",
        reversed_meaning: "관계 안에서 자신의 목소리를 잃어가고 있습니다. 조화는 희생으로 만드는 것이 아닙니다. 솔직하지 못한 감정이 쌓이면 균열은 더 깊어집니다.",
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 7,
        name_ko: "전차",
        name_en: "The Chariot",
        arcana: ArcanaType::Major,
        suit: None,
        number: 7,
        keywords: &["의지", "승리", "전진"],
        upright_meaning: "내면의 두 힘이 같은 방향을 향할 때 그 무엇도 당신을 막을 수 없습니다. 확신과 추진력이 모두 갖춰진 지금이 전진할 최적의 순간입니다. 망설임은 나중에, 먼저 달리세요.",
        reversed_meaning: "속도는 빠른데 방향을 잃은 상태입니다. 힘이 분산되면 아무리 열심히 달려도 제자리입니다. 잠시 멈추고 나침반을 다시 확인하세요.",
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 8,
        name_ko: "힘",
        name_en: "Strength",
        arcana: ArcanaType::Major,
        suit: None,
        number: 8,
        keywords: &["용기", "인내", "내면의 힘"],
        upright_meaning: "진짜 힘은 억누르는 데 있지 않고 부드럽게 다스리는 데 있습니다. 두려움과 불안을 밀어내지 말고 그것을 손으로 쥐듯 감싸안으세요. 그 순간 당신이 가장 강해집니다.",
        reversed_meaning: "자신에 대한 믿음이 바닥을 치고 있습니다. 약해 보이는 것이 두려워 오히려 더 긴장하고 있지는 않은지 살펴보세요. 취약함을 인정하는 것이 회복의 시작입니다.",
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 9,
        name_ko: "은둔자",
        name_en: "The Hermit",
        arcana: ArcanaType::Major,
        suit: None,
        number: 9,
        keywords: &["성찰", "고독", "지혜"],
        upright_meaning: "외부의 소음을 줄이고 자신만의 등불을 들어야 할 때입니다. 군중의 답이 아닌 내면의 진실을 찾는 여정은 혼자만이 걸을 수 있습니다. 고독은 벌이 아니라 성장의 공간입니다.",
        reversed_meaning: "혼자만의 시간이 성찰이 아니라 도피가 되고 있습니다. 세상과의 연결을 끊으면 지혜도 함께 멈춥니다. 손을 내밀어 줄 누군가가 지금 곁에 있습니다.",
        element: TarotElement::Earth,
        ohang: Ohang::Earth,
    },
    TarotCard {
        id: 10,
        name_ko: "운명의 수레바퀴",
        name_en: "Wheel of Fortune",
        arcana: ArcanaType::Major,
        suit: None,
        number: 10,
        keywords: &["변화", "순환", "운명"],
        upright_meaning: "바퀴가 돌아 당신의 자리가 바뀌고 있습니다. 이 변화는 우연이 아닌 흐름의 일부입니다. 준비된 사람만이 기회를 기회로 알아봅니다.",
        reversed_meaning: "흐름을 거슬러 제자리에 머물려 할수록 저항의 무게만 커집니다. 좋지 않은 순환이라면 먼저 내가 무엇을 반복하고 있는지 봐야 합니다. 패턴을 바꾸면 바퀴도 바뀝니다.",
        element: TarotElement::Earth,
        ohang: Ohang::Earth,
    },
    TarotCard {
        id: 11,
        name_ko: "정의",
        name_en: "Justice",
        arcana: ArcanaType::Major,
        suit: None,
        number: 11,
        keywords: &["균형", "공정", "진실"],
        upright_meaning: "저울은 언제나 진실 쪽으로 기웁니다. 지금 내린 결정이 나중에도 정당하다고 말할 수 있을지 묻고 나서 행동하세요. 공정함은 결과가 아니라 과정에서 드러납니다.",
        reversed_meaning: "보고 싶은 것만 보고 있지는 않은지 돌아보세요. 책임 회피나 편향된 판단이 상황을 더 얽히게 만들고 있습니다. 진실과 마주하는 용기가 균형을 되찾아줍니다.",
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 12,
        name_ko: "매달린 사람",
        name_en: "The Hanged Man",
        arcana: ArcanaType::Major,
        suit: None,
        number: 12,
        keywords: &["희생", "관점 전환", "기다림"],
        upright_meaning: "거꾸로 매달린 사람만이 세상을 다른 각도로 볼 수 있습니다. 지금 멈춰 있는 것이 실패가 아니라 필요한 전환의 시간입니다. 내려놓을 때 비로소 자유가 찾아옵니다.",
        reversed_meaning: "버텨야 할 이유보다 놓아야 할 이유가 더 많습니다. 불필요한 대가를 치르면서 스스로를 소모하고 있습니다. 다른 방법이 있다는 것을 인정하는 것이 용기입니다.",
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 13,
        name_ko: "죽음",
        name_en: "Death",
        arcana: ArcanaType::Major,
        suit: None,
        number: 13,
        keywords: &["변환", "끝과 시작", "해방"],
        upright_meaning: "지금 끝나는 것이 있어야 새것이 시작될 자리가 생깁니다. 두려워하는 것은 죽음이 아니라 변화입니다. 손을 펴고 흘려보내는 순간이 진정한 해방입니다.",
        reversed_meaning: "이미 끝났어야 할 것을 붙들고 있습니다. 과거의 모습으로 돌아가려는 몸부림이 현재를 좀먹고 있습니다. 지나간 것에 작별 인사를 건넬 때가 되었습니다.",
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 14,
        name_ko: "절제",
        name_en: "Temperance",
        arcana: ArcanaType::Major,
        suit: None,
        number: 14,
        keywords: &["조화", "균형", "인내"],
        upright_meaning: "두 잔 사이를 흐르는 물처럼 차고 뜨거움이 섞여 딱 알맞은 온도가 됩니다. 극단을 피하고 흐름 속에서 조화를 찾는 것이 지금 당신에게 가장 필요한 지혜입니다. 서두르지 않는 것 자체가 최선입니다.",
        reversed_meaning: "한쪽으로 지나치게 기울어 있습니다. 과하거나 모자란 것이 쌓여 불균형이 커지고 있습니다. 무엇을 조금 덜어내야 균형이 돌아올지 살펴보세요.",
        element: TarotElement::Earth,
        ohang: Ohang::Earth,
    },
    TarotCard {
        id: 15,
        name_ko: "악마",
        name_en: "The Devil",
        arcana: ArcanaType::Major,
        suit: None,
        number: 15,
        keywords: &["속박", "유혹", "집착"],
        upright_meaning: "사슬이 생각보다 느슨합니다. 벗어날 수 없다는 믿음 자체가 가장 강한 족쇄입니다. 무엇이 당신을 붙들고 있는지 정확히 보는 것이 자유를 향한 첫 걸음입니다.",
        reversed_meaning: "오랫동안 당신을 옭아매던 것에서 서서히 풀려나고 있습니다. 중독적 패턴이나 독이 된 관계에 마침내 단호해질 힘이 생겼습니다. 자유는 이미 시작되었습니다.",
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 16,
        name_ko: "탑",
        name_en: "The Tower",
        arcana: ArcanaType::Major,
        suit: None,
        number: 16,
        keywords: &["파괴", "급변", "해방"],
        upright_meaning: "번개는 썩은 것을 태워 새로운 기반을 드러냅니다. 예상치 못한 충격이 찾아오더라도 그것이 거짓 위에 세워진 것을 무너뜨리는 과정임을 기억하세요. 진실 위에 다시 세우면 더 단단해집니다.",
        reversed_meaning: "큰 충격은 비껴갔지만 근본 원인은 아직 남아있습니다. 서서히 균열이 쌓이는 중이니 불편한 문제를 더 미루지 마세요. 작은 붕괴가 더 큰 붕괴를 막아줍니다.",
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 17,
        name_ko: "별",
        name_en: "The Star",
        arcana: ArcanaType::Major,
        suit: None,
        number: 17,
        keywords: &["희망", "영감", "치유"],
        upright_meaning: "폭풍이 지나간 밤하늘에 별이 가장 밝게 빛납니다. 힘들었던 시간이 치유와 회복의 씨앗이 되고 있습니다. 꿈을 향해 천천히 나아가도 괜찮습니다. 별은 기다려 줍니다.",
        reversed_meaning: "희망이 닳아 믿음이 흔들리고 있습니다. 하지만 별이 구름에 가려도 사라진 것이 아닌 것처럼 가능성은 여전히 있습니다. 작고 가까운 것에서부터 희망을 다시 켜세요.",
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 18,
        name_ko: "달",
        name_en: "The Moon",
        arcana: ArcanaType::Major,
        suit: None,
        number: 18,
        keywords: &["환상", "불안", "무의식"],
        upright_meaning: "안개가 짙은 밤길을 걷고 있습니다. 발걸음을 멈추지 말되 보이는 것을 전부라고 믿지 마세요. 무의식이 보내는 신호와 꿈의 언어에 귀를 기울이면 안개 너머가 조금씩 보입니다.",
        reversed_meaning: "오랫동안 당신을 괴롭히던 불안과 혼란이 걷히기 시작합니다. 두려움이 만들어낸 그림자의 크기가 실제보다 컸음을 알게 될 것입니다. 이제 더 명확하게 볼 수 있습니다.",
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 19,
        name_ko: "태양",
        name_en: "The Sun",
        arcana: ArcanaType::Major,
        suit: None,
        number: 19,
        keywords: &["성공", "기쁨", "활력"],
        upright_meaning: "숨길 필요도, 꾸밀 필요도 없이 있는 그대로 빛나는 시간입니다. 노력이 빛을 발하고 기쁨이 자연스럽게 넘쳐나는 계절입니다. 지금 이 순간을 온전히 즐기세요.",
        reversed_meaning: "빛이 잠시 흐려지는 계절이지만 태양은 사라지지 않았습니다. 기대가 너무 높거나 비교가 기쁨을 흐리고 있지는 않은지 돌아보세요. 내면의 작은 기쁨부터 다시 찾아보세요.",
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 20,
        name_ko: "심판",
        name_en: "Judgement",
        arcana: ArcanaType::Major,
        suit: None,
        number: 20,
        keywords: &["부활", "자각", "결산"],
        upright_meaning: "나팔 소리처럼 선명한 깨달음이 찾아옵니다. 지나온 시간을 평가할 때 가장 엄중한 심판관은 바로 자기 자신입니다. 과거를 정산하고 소명을 새롭게 세울 때입니다.",
        reversed_meaning: "지나간 실수의 무게가 지금 당신을 억누르고 있습니다. 스스로를 심판하는 목소리가 너무 가혹합니다. 용서는 과거를 지우는 것이 아니라 그 무게를 내려놓는 것입니다.",
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 21,
        name_ko: "세계",
        name_en: "The World",
        arcana: ArcanaType::Major,
        suit: None,
        number: 21,
        keywords: &["완성", "통합", "성취"],
        upright_meaning: "긴 여정이 아름다운 완성에 이르렀습니다. 흩어졌던 모든 조각이 하나의 완전한 그림이 되는 순간입니다. 이 성취를 충분히 누리고, 다음 여정을 위한 숨을 고르세요.",
        reversed_meaning: "결승선이 코앞인데 아직 무언가 마무리되지 않은 느낌이 있습니다. 완성을 서두르기보다 마지막 빈칸을 채우는 데 집중하세요. 조급함이 지금까지의 노력을 흐릿하게 만들 수 있습니다.",
        element: TarotElement::Earth,
        ohang: Ohang::Earth,
    },
];

/// 완드(Wands) 수트 14장 - 불(Fire) - 화(火)
static WANDS: [TarotCard; 14] = [
    TarotCard {
        id: 22,
        name_ko: "완드 에이스",
        name_en: "Ace of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 1,
        keywords: &["영감", "시작", "잠재력"],
        upright_meaning: "새로운 열정의 불씨가 피어오릅니다. 창조적 에너지가 넘치는 시기이니 과감하게 시작하세요.",
        reversed_meaning: "시작의 에너지가 막혀 있습니다. 의욕은 있으나 방향이 불분명합니다. 내면의 열정을 다시 찾아보세요.",
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 23,
        name_ko: "완드 2",
        name_en: "Two of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 2,
        keywords: &["계획", "결정", "미래"],
        upright_meaning: "미래를 내다보며 계획을 세울 때입니다. 두 가지 선택지 중 하나를 골라야 합니다. 넓은 시야로 결정하세요.",
        reversed_meaning: "계획이 지연되고 있습니다. 결정을 미루고 있지는 않은지 돌아보세요. 안전한 선택만 고집하면 성장이 멈춥니다.",
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 24,
        name_ko: "완드 3",
        name_en: "Three of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 3,
        keywords: &["확장", "전망", "기회"],
        upright_meaning: "노력의 첫 결실이 보이기 시작합니다. 더 넓은 세계로 나아갈 기회가 열리고 있습니다.",
        reversed_meaning: "기대한 결과가 나오지 않아 실망할 수 있습니다. 인내심을 가지세요. 방향을 재점검할 필요가 있습니다.",
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 25,
        name_ko: "완드 4",
        name_en: "Four of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 4,
        keywords: &["축하", "안정", "화합"],
        upright_meaning: "기쁜 소식과 축하할 일이 생깁니다. 안정된 기반 위에서 행복을 누리는 시기입니다.",
        reversed_meaning: "내면의 불안이 기쁨을 가로막고 있습니다. 가정이나 관계에서 갈등이 있을 수 있습니다. 소통으로 해결하세요.",
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 26,
        name_ko: "완드 5",
        name_en: "Five of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 5,
        keywords: &["경쟁", "갈등", "도전"],
        upright_meaning: "경쟁과 갈등이 존재하지만 이를 통해 성장할 수 있습니다. 건설적인 방향으로 에너지를 쏟으세요.",
        reversed_meaning: "불필요한 다툼을 피하세요. 갈등을 해소할 방법을 찾아야 합니다. 양보가 때로는 승리입니다.",
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 27,
        name_ko: "완드 6",
        name_en: "Six of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 6,
        keywords: &["승리", "인정", "자신감"],
        upright_meaning: "노력이 인정받는 순간입니다. 자신감을 가지세요. 리더십을 발휘할 좋은 시기입니다.",
        reversed_meaning: "자만심에 주의하세요. 타인의 공로를 무시하고 있지는 않은지 돌아보세요. 겸손이 필요한 때입니다.",
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 28,
        name_ko: "완드 7",
        name_en: "Seven of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 7,
        keywords: &["방어", "도전", "끈기"],
        upright_meaning: "사방에서 도전이 쏟아지지만 당신은 이겨낼 수 있습니다. 자신의 입장을 굳건히 지키세요.",
        reversed_meaning: "압박감에 지쳐 포기하고 싶을 수 있습니다. 모든 싸움을 할 필요는 없습니다. 전략적으로 판단하세요.",
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 29,
        name_ko: "완드 8",
        name_en: "Eight of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 8,
        keywords: &["속도", "진행", "소통"],
        upright_meaning: "일이 빠르게 진행됩니다. 기다리던 소식이 도착할 수 있습니다. 흐름을 타고 앞으로 나아가세요.",
        reversed_meaning: "진행이 지연되거나 혼란이 생길 수 있습니다. 서두르지 마세요. 정확한 소통이 중요합니다.",
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 30,
        name_ko: "완드 9",
        name_en: "Nine of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 9,
        keywords: &["인내", "경계", "회복력"],
        upright_meaning: "지치더라도 포기하지 마세요. 마지막 시련이 남아 있지만 당신은 충분히 강합니다. 끝까지 버텨내세요.",
        reversed_meaning: "지나친 경계심이 에너지를 소모하고 있습니다. 모든 것에 방어적일 필요는 없습니다. 쉬어갈 줄도 알아야 합니다.",
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 31,
        name_ko: "완드 10",
        name_en: "Ten of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 10,
        keywords: &["부담", "책임", "완수"],
        upright_meaning: "무거운 짐을 지고 있지만 목표가 가까이 있습니다. 책임감을 가지되 필요하다면 도움을 구하세요.",
        reversed_meaning: "불필요한 부담을 내려놓으세요. 혼자 다 짊어질 필요가 없습니다. 위임하고 나누는 것이 지혜입니다.",
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 32,
        name_ko: "완드 시종",
        name_en: "Page of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 11,
        keywords: &["탐험", "열정", "발견"],
        upright_meaning: "새로운 것에 대한 호기심과 열정이 피어나고 있습니다. 자유롭게 탐험하세요. 좋은 소식이 올 수 있습니다.",
        reversed_meaning: "열정이 산만함으로 흐르고 있습니다. 하나에 집중하세요. 충동적인 행동은 삼가세요.",
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 33,
        name_ko: "완드 기사",
        name_en: "Knight of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 12,
        keywords: &["행동", "모험", "에너지"],
        upright_meaning: "과감한 행동이 필요한 시기입니다. 열정적으로 목표를 향해 돌진하세요. 모험을 두려워하지 마세요.",
        reversed_meaning: "성급한 판단을 주의하세요. 에너지가 방향 없이 흩어지고 있습니다. 계획을 세운 후 행동하세요.",
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 34,
        name_ko: "완드 여왕",
        name_en: "Queen of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 13,
        keywords: &["자신감", "매력", "따뜻함"],
        upright_meaning: "자신감과 매력이 넘치는 시기입니다. 따뜻한 리더십으로 주변을 이끌 수 있습니다. 당신의 빛을 발하세요.",
        reversed_meaning: "질투심이나 자기 의심이 에너지를 소모합니다. 타인과 비교하지 마세요. 자신의 가치를 믿으세요.",
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
    TarotCard {
        id: 35,
        name_ko: "완드 왕",
        name_en: "King of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 14,
        keywords: &["리더십", "비전", "성취"],
        upright_meaning: "리더십을 발휘할 때입니다. 큰 비전을 품고 주변을 이끌어가세요. 결단력 있는 행동이 성공을 가져옵니다.",
        reversed_meaning: "독단적인 태도에 주의하세요. 리더십이 폭군으로 변하지 않도록 경계하세요. 경청하는 자세가 필요합니다.",
        element: TarotElement::Fire,
        ohang: Ohang::Fire,
    },
];

/// 컵(Cups) 수트 14장 - 물(Water) - 수(水)
static CUPS: [TarotCard; 14] = [
    TarotCard {
        id: 36,
        name_ko: "컵 에이스",
        name_en: "Ace of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 1,
        keywords: &["새 사랑", "감정", "직관"],
        upright_meaning: "새로운 사랑이나 깊은 감정적 교류가 시작됩니다. 마음을 열고 흘러오는 감정을 받아들이세요.",
        reversed_meaning: "감정을 억누르고 있습니다. 마음의 문을 닫으면 좋은 기회도 놓칠 수 있습니다. 감정을 솔직히 표현하세요.",
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 37,
        name_ko: "컵 2",
        name_en: "Two of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 2,
        keywords: &["연합", "파트너십", "사랑"],
        upright_meaning: "두 사람 사이에 깊은 유대가 형성됩니다. 사랑, 우정, 비즈니스 파트너십 모두에 좋은 시기입니다.",
        reversed_meaning: "관계에 균열이 생기고 있습니다. 소통의 부재가 문제입니다. 상대방의 입장을 이해하려 노력하세요.",
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 38,
        name_ko: "컵 3",
        name_en: "Three of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 3,
        keywords: &["축하", "우정", "기쁨"],
        upright_meaning: "함께 기뻐할 일이 생깁니다. 소중한 사람들과의 유대가 더 깊어지는 시기입니다. 함께하는 기쁨을 나누세요.",
        reversed_meaning: "사교적 에너지가 과도하거나 부족합니다. 인간관계에서 피로를 느낄 수 있습니다. 진정한 관계에 집중하세요.",
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 39,
        name_ko: "컵 4",
        name_en: "Four of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 4,
        keywords: &["권태", "무관심", "내성"],
        upright_meaning: "현재에 만족하지 못하고 있습니다. 하지만 눈앞에 놓인 기회를 놓치고 있을 수 있습니다. 시야를 넓히세요.",
        reversed_meaning: "새로운 가능성에 눈을 뜨기 시작합니다. 무기력에서 벗어나 다시 의욕을 찾는 시기입니다.",
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 40,
        name_ko: "컵 5",
        name_en: "Five of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 5,
        keywords: &["상실", "슬픔", "후회"],
        upright_meaning: "상실감과 슬픔의 시기이지만, 아직 남아 있는 것에 주목하세요. 잃은 것에만 집중하면 남은 기회를 놓칩니다.",
        reversed_meaning: "슬픔에서 벗어나 회복하기 시작합니다. 과거를 받아들이고 앞으로 나아갈 준비가 되어가고 있습니다.",
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 41,
        name_ko: "컵 6",
        name_en: "Six of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 6,
        keywords: &["추억", "순수", "향수"],
        upright_meaning: "따뜻한 추억이 마음을 어루만집니다. 과거의 인연이 다시 이어질 수 있습니다. 순수했던 마음을 되찾으세요.",
        reversed_meaning: "과거에 지나치게 얽매여 있습니다. 향수에 빠져 현재를 놓치고 있습니다. 앞을 바라보세요.",
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 42,
        name_ko: "컵 7",
        name_en: "Seven of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 7,
        keywords: &["환상", "선택", "상상"],
        upright_meaning: "많은 선택지가 눈앞에 펼쳐져 있습니다. 환상과 현실을 구분하세요. 진정으로 원하는 것을 선택하세요.",
        reversed_meaning: "공상에서 벗어나 현실을 직시하고 있습니다. 실현 가능한 목표를 설정할 때입니다.",
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 43,
        name_ko: "컵 8",
        name_en: "Eight of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 8,
        keywords: &["떠남", "탐색", "전환"],
        upright_meaning: "현재 상황을 떠나 더 깊은 의미를 찾아 나설 때입니다. 용기 있는 전환이 새로운 성장을 가져옵니다.",
        reversed_meaning: "떠나야 할 때 머무르고 있습니다. 변화가 두려워 현재에 안주하고 있습니다. 마음의 소리를 따르세요.",
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 44,
        name_ko: "컵 9",
        name_en: "Nine of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 9,
        keywords: &["만족", "소원", "행복"],
        upright_meaning: "소원이 이루어지는 시기입니다. 감정적으로 충만하고 만족스러운 때입니다. 감사하는 마음을 잊지 마세요.",
        reversed_meaning: "물질적 만족이 감정적 공허를 채우지 못합니다. 진정한 행복이 무엇인지 다시 생각해보세요.",
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 45,
        name_ko: "컵 10",
        name_en: "Ten of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 10,
        keywords: &["행복", "가족", "조화"],
        upright_meaning: "가족과 사랑하는 사람들과 함께하는 완전한 행복의 시기입니다. 감정적 안정과 조화를 느낄 수 있습니다.",
        reversed_meaning: "가정이나 관계에 불화가 있습니다. 이상적인 모습에 집착하기보다 현실적인 조화를 추구하세요.",
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 46,
        name_ko: "컵 시종",
        name_en: "Page of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 11,
        keywords: &["감성", "직관", "메시지"],
        upright_meaning: "감성이 풍부해지는 시기입니다. 직관적인 메시지에 귀를 기울이세요. 창의적 영감이 찾아올 수 있습니다.",
        reversed_meaning: "감정에 휘둘리고 있습니다. 비현실적인 기대를 하고 있지는 않은지 점검하세요.",
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 47,
        name_ko: "컵 기사",
        name_en: "Knight of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 12,
        keywords: &["로맨스", "매력", "제안"],
        upright_meaning: "매력적인 제안이나 로맨틱한 만남이 찾아올 수 있습니다. 감정에 솔직하되 현실을 놓치지 마세요.",
        reversed_meaning: "감정적 판단이 현실 감각을 흐리게 합니다. 달콤한 말 뒤에 숨은 진실을 파악하세요.",
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 48,
        name_ko: "컵 여왕",
        name_en: "Queen of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 13,
        keywords: &["공감", "돌봄", "직관"],
        upright_meaning: "깊은 공감 능력과 직관이 발휘되는 시기입니다. 따뜻한 마음으로 주변을 감싸안으세요.",
        reversed_meaning: "감정적으로 지쳐 있습니다. 타인을 돌보느라 자신을 소홀히 하고 있습니다. 자기 돌봄이 먼저입니다.",
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
    TarotCard {
        id: 49,
        name_ko: "컵 왕",
        name_en: "King of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 14,
        keywords: &["감정적 균형", "지혜", "관용"],
        upright_meaning: "감정과 이성의 균형을 잘 유지하고 있습니다. 관용과 지혜로 주변 사람들에게 든든한 버팀목이 되세요.",
        reversed_meaning: "감정을 억누르거나 감정적으로 조종하려는 경향에 주의하세요. 진솔한 소통이 필요합니다.",
        element: TarotElement::Water,
        ohang: Ohang::Water,
    },
];

/// 소드(Swords) 수트 14장 - 바람(Air) - 목(木)
static SWORDS: [TarotCard; 14] = [
    TarotCard {
        id: 50,
        name_ko: "소드 에이스",
        name_en: "Ace of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 1,
        keywords: &["명확함", "진실", "돌파구"],
        upright_meaning: "진실이 명확해지는 순간입니다. 새로운 아이디어와 명쾌한 판단력이 생깁니다. 정의로운 결단을 내리세요.",
        reversed_meaning: "혼란과 오해가 진실을 가리고 있습니다. 불분명한 상황에서 성급한 판단을 내리지 마세요.",
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 51,
        name_ko: "소드 2",
        name_en: "Two of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 2,
        keywords: &["균형", "결정", "교착"],
        upright_meaning: "두 가지 사이에서 결정을 내려야 합니다. 감정을 배제하고 이성적으로 판단하세요. 교착 상태를 깨뜨릴 용기가 필요합니다.",
        reversed_meaning: "미루던 결정을 내릴 때가 왔습니다. 진실을 외면하지 마세요. 직면하는 것이 해결의 시작입니다.",
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 52,
        name_ko: "소드 3",
        name_en: "Three of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 3,
        keywords: &["이별", "슬픔", "상처"],
        upright_meaning: "마음의 상처를 겪을 수 있습니다. 이별이나 배신의 아픔이 있지만, 치유의 과정은 이미 시작되었습니다.",
        reversed_meaning: "상처에서 회복되고 있습니다. 아픔을 인정하고 받아들이면 치유가 빨라집니다. 용서가 자유를 줍니다.",
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 53,
        name_ko: "소드 4",
        name_en: "Four of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 4,
        keywords: &["휴식", "회복", "명상"],
        upright_meaning: "지금은 쉬어야 할 때입니다. 몸과 마음의 회복을 위한 시간을 가지세요. 충전 후에 다시 일어설 수 있습니다.",
        reversed_meaning: "쉬어야 할 때 억지로 움직이고 있습니다. 번아웃에 주의하세요. 진정한 휴식이 필요합니다.",
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 54,
        name_ko: "소드 5",
        name_en: "Five of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 5,
        keywords: &["갈등", "패배", "이기심"],
        upright_meaning: "이기더라도 잃는 것이 있을 수 있습니다. 승부에 집착하기보다 더 큰 그림을 보세요. 화해가 더 큰 승리입니다.",
        reversed_meaning: "과거의 갈등을 정리할 때입니다. 복수심을 내려놓으세요. 평화를 선택하는 것도 강함입니다.",
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 55,
        name_ko: "소드 6",
        name_en: "Six of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 6,
        keywords: &["전환", "이동", "치유"],
        upright_meaning: "어려운 상황에서 벗어나 평온한 곳으로 이동하는 시기입니다. 변화를 받아들이면 새로운 평화를 찾을 수 있습니다.",
        reversed_meaning: "변화를 거부하고 있습니다. 고통스러운 상황에 머무르는 것은 더 큰 상처를 남깁니다. 용기를 내세요.",
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 56,
        name_ko: "소드 7",
        name_en: "Seven of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 7,
        keywords: &["전략", "기만", "독립"],
        upright_meaning: "전략적 사고가 필요합니다. 모든 것을 드러내기보다 신중하게 움직이세요. 독자적인 길을 택할 수도 있습니다.",
        reversed_meaning: "비밀이 드러날 수 있습니다. 속임수나 자기 기만에 주의하세요. 정직한 방법이 결국 최선입니다.",
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 57,
        name_ko: "소드 8",
        name_en: "Eight of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 8,
        keywords: &["제약", "무력감", "자기 제한"],
        upright_meaning: "스스로 만든 한계에 갇혀 있습니다. 실제로는 빠져나올 수 있는 방법이 있습니다. 두려움을 직시하세요.",
        reversed_meaning: "제약에서 벗어나기 시작합니다. 새로운 관점으로 해결책을 발견하게 됩니다. 자유가 가까이 있습니다.",
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 58,
        name_ko: "소드 9",
        name_en: "Nine of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 9,
        keywords: &["불안", "걱정", "악몽"],
        upright_meaning: "걱정과 불안이 밤잠을 설치게 합니다. 하지만 두려움의 대부분은 실제보다 과장되어 있습니다. 현실을 직시하세요.",
        reversed_meaning: "불안에서 벗어나고 있습니다. 과도한 걱정이 불필요했음을 깨닫게 됩니다. 마음의 평화를 찾으세요.",
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 59,
        name_ko: "소드 10",
        name_en: "Ten of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 10,
        keywords: &["종결", "최저점", "새벽"],
        upright_meaning: "가장 힘든 시기가 끝나가고 있습니다. 바닥을 찍었으니 이제 올라갈 일만 남았습니다. 새로운 시작이 기다립니다.",
        reversed_meaning: "최악의 상황을 면할 수 있습니다. 완전한 몰락을 피했으니 회복에 집중하세요.",
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 60,
        name_ko: "소드 시종",
        name_en: "Page of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 11,
        keywords: &["호기심", "관찰", "경계"],
        upright_meaning: "예리한 관찰력으로 상황을 파악하세요. 새로운 정보를 수집하고 분석할 때입니다. 진실을 추구하세요.",
        reversed_meaning: "가십이나 험담에 휘말리지 마세요. 날카로운 말이 상처를 줄 수 있습니다. 말을 아끼세요.",
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 61,
        name_ko: "소드 기사",
        name_en: "Knight of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 12,
        keywords: &["결단", "돌진", "지성"],
        upright_meaning: "결단력 있게 목표를 향해 돌진하세요. 명확한 사고로 장애물을 돌파할 수 있습니다. 지금이 행동할 때입니다.",
        reversed_meaning: "충동적인 행동이 문제를 일으킵니다. 생각 없이 말하거나 행동하면 후회할 수 있습니다. 숙고하세요.",
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 62,
        name_ko: "소드 여왕",
        name_en: "Queen of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 13,
        keywords: &["명석함", "독립", "솔직함"],
        upright_meaning: "명석한 판단력과 독립적인 사고가 빛나는 시기입니다. 감정에 흔들리지 않고 공정하게 상황을 바라보세요.",
        reversed_meaning: "냉정함이 무심함으로 비칠 수 있습니다. 이성과 감정의 균형을 찾으세요. 비판만으로는 관계를 유지할 수 없습니다.",
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
    TarotCard {
        id: 63,
        name_ko: "소드 왕",
        name_en: "King of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 14,
        keywords: &["권위", "진실", "판단력"],
        upright_meaning: "명확한 사고와 공정한 판단으로 상황을 주도하세요. 진실에 기반한 리더십이 요구됩니다.",
        reversed_meaning: "권력을 남용하거나 지나치게 비판적일 수 있습니다. 독선에 빠지지 마세요. 관용의 자세가 필요합니다.",
        element: TarotElement::Air,
        ohang: Ohang::Wood,
    },
];

/// 펜타클(Pentacles) 수트 14장 - 땅(Earth) - 금(金)
static PENTACLES: [TarotCard; 14] = [
    TarotCard {
        id: 64,
        name_ko: "펜타클 에이스",
        name_en: "Ace of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 1,
        keywords: &["기회", "번영", "시작"],
        upright_meaning: "새로운 재정적 기회나 물질적 시작이 찾아옵니다. 씨앗을 심을 좋은 때입니다. 현실적인 목표를 세우세요.",
        reversed_meaning: "좋은 기회를 놓치거나 계획이 무산될 수 있습니다. 물질에 지나치게 집착하지 마세요.",
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 65,
        name_ko: "펜타클 2",
        name_en: "Two of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 2,
        keywords: &["균형", "적응", "유연함"],
        upright_meaning: "여러 가지를 동시에 다루어야 하는 시기입니다. 유연하게 대처하면 균형을 유지할 수 있습니다.",
        reversed_meaning: "너무 많은 것을 떠안고 있습니다. 우선순위를 정하세요. 무리하면 모든 것을 놓칠 수 있습니다.",
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 66,
        name_ko: "펜타클 3",
        name_en: "Three of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 3,
        keywords: &["팀워크", "기술", "협력"],
        upright_meaning: "협력과 팀워크가 좋은 결과를 가져옵니다. 전문성을 발휘하고 다른 사람의 의견을 존중하세요.",
        reversed_meaning: "팀 내 갈등이나 소통 부재가 문제입니다. 각자의 역할을 명확히 하고 협력 방법을 개선하세요.",
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 67,
        name_ko: "펜타클 4",
        name_en: "Four of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 4,
        keywords: &["안정", "절약", "집착"],
        upright_meaning: "재정적 안정을 추구하는 시기입니다. 저축과 절약이 미래를 위한 투자입니다. 현명하게 관리하세요.",
        reversed_meaning: "물질에 대한 집착이 행복을 가로막고 있습니다. 베풂이 더 큰 풍요를 가져옵니다. 손을 펴세요.",
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 68,
        name_ko: "펜타클 5",
        name_en: "Five of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 5,
        keywords: &["어려움", "소외", "인내"],
        upright_meaning: "경제적 또는 정서적으로 어려운 시기입니다. 하지만 도움의 손길은 가까이에 있습니다. 포기하지 마세요.",
        reversed_meaning: "어려운 시기가 끝나가고 있습니다. 회복의 빛이 보이기 시작합니다. 도움을 받아들이세요.",
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 69,
        name_ko: "펜타클 6",
        name_en: "Six of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 6,
        keywords: &["나눔", "관대함", "공정"],
        upright_meaning: "나누는 즐거움을 경험할 수 있습니다. 도움을 주거나 받는 균형 잡힌 관계를 유지하세요.",
        reversed_meaning: "주고받는 것의 불균형이 있습니다. 조건 없는 선의인지 점검하세요. 의존 관계에 주의하세요.",
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 70,
        name_ko: "펜타클 7",
        name_en: "Seven of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 7,
        keywords: &["평가", "인내", "수확"],
        upright_meaning: "지금까지의 노력을 되돌아볼 때입니다. 결실이 맺히려면 조금 더 인내가 필요합니다. 장기적 관점을 유지하세요.",
        reversed_meaning: "노력 대비 결과가 미미하여 좌절할 수 있습니다. 전략을 수정할지, 더 기다릴지 결정하세요.",
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 71,
        name_ko: "펜타클 8",
        name_en: "Eight of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 8,
        keywords: &["장인정신", "근면", "숙련"],
        upright_meaning: "꾸준한 노력과 성실함이 빛을 발합니다. 기술을 갈고닦을 좋은 시기입니다. 집중과 반복이 완벽을 만듭니다.",
        reversed_meaning: "단조로운 반복에 지쳐 있습니다. 목표를 잃고 있거나 완벽주의에 빠져 있지는 않은지 점검하세요.",
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 72,
        name_ko: "펜타클 9",
        name_en: "Nine of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 9,
        keywords: &["풍요", "독립", "자족"],
        upright_meaning: "노력의 결실을 누리는 시기입니다. 독립적이고 풍요로운 삶을 즐기세요. 자신에 대한 보상을 아끼지 마세요.",
        reversed_meaning: "외적인 풍요와 내적 만족 사이에 괴리가 있습니다. 물질만으로는 채울 수 없는 것이 있습니다.",
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 73,
        name_ko: "펜타클 10",
        name_en: "Ten of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 10,
        keywords: &["유산", "가문", "완성"],
        upright_meaning: "세대를 이어가는 풍요와 안정을 상징합니다. 가족의 유대가 강화되고 장기적 안정이 찾아옵니다.",
        reversed_meaning: "가족 간 재정 문제나 유산을 둘러싼 갈등에 주의하세요. 물질보다 관계가 중요함을 기억하세요.",
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 74,
        name_ko: "펜타클 시종",
        name_en: "Page of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 11,
        keywords: &["학습", "기회", "성실"],
        upright_meaning: "새로운 배움이나 재정적 기회가 나타납니다. 성실하게 기초를 다지세요. 작은 시작이 큰 성공으로 이어집니다.",
        reversed_meaning: "기회를 놓치거나 계획이 흐지부지됩니다. 현실적인 목표를 세우고 실행에 옮기세요.",
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 75,
        name_ko: "펜타클 기사",
        name_en: "Knight of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 12,
        keywords: &["책임감", "꾸준함", "신뢰"],
        upright_meaning: "묵묵히 맡은 바를 수행하는 시기입니다. 화려하지 않지만 꾸준한 노력이 결국 성공을 가져옵니다.",
        reversed_meaning: "지나치게 보수적이거나 융통성이 부족합니다. 변화를 두려워하지 마세요. 새로운 방법도 고려하세요.",
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 76,
        name_ko: "펜타클 여왕",
        name_en: "Queen of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 13,
        keywords: &["돌봄", "풍요", "현실감"],
        upright_meaning: "현실적이면서도 따뜻한 돌봄의 에너지가 넘칩니다. 실용적인 방법으로 주변을 풍요롭게 만들 수 있습니다.",
        reversed_meaning: "일과 돌봄 사이의 균형이 무너져 있습니다. 자신의 안녕을 챙기면서 타인도 돌보는 방법을 찾으세요.",
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
    TarotCard {
        id: 77,
        name_ko: "펜타클 왕",
        name_en: "King of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 14,
        keywords: &["성공", "안정", "풍요"],
        upright_meaning: "물질적 성공과 안정의 정점에 있습니다. 현명한 판단으로 부를 관리하세요. 관대함이 더 큰 풍요를 가져옵니다.",
        reversed_meaning: "물질에 대한 탐욕이 지나칩니다. 돈이 인간관계보다 중요해지고 있지는 않은지 돌아보세요.",
        element: TarotElement::Earth,
        ohang: Ohang::Metal,
    },
];

/// 전체 78장 카드를 반환하는 함수
pub fn all_cards() -> &'static [TarotCard] {
    static ALL_CARDS: std::sync::OnceLock<Vec<TarotCard>> = std::sync::OnceLock::new();
    ALL_CARDS.get_or_init(|| {
        let mut cards = Vec::with_capacity(78);
        cards.extend_from_slice(&MAJOR_ARCANA);
        cards.extend_from_slice(&WANDS);
        cards.extend_from_slice(&CUPS);
        cards.extend_from_slice(&SWORDS);
        cards.extend_from_slice(&PENTACLES);
        cards
    })
}

/// 카드 ID로 카드 조회
pub fn get_card(id: u8) -> Option<&'static TarotCard> {
    all_cards().get(id as usize)
}
